version: "2.1"
orbs:
  node: circleci/node@4.8.1
  heroku: circleci/heroku@1.2.6
jobs:
  compile-and-deploy:
    executor:
      name: node/default
      tag: "16.13"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn compile
      - heroku/deploy-via-git:
          filters:
            branches:
              only:
                - master
workflows:
  deploy:
    jobs:
      - compile-and-deploy
